version: "3.4"

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - horcup-sqldata:/var/opt/mssql

  rabbitmq:
    ports:
      - "15672:15672"
      - "5672:5672"

  identity-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=${HORCUP_AZURE_IDENTITY_DB:-Server=sqldata;Database=HorCup.Identity;User Id=sa;Password=Pass@word}
    ports:
      - "5002:80"

  games-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${HORCUP_AZURE_GAMES_DB:-Server=sqldata;Database=HorCup.Games;User Id=sa;Password=Pass@word}
    ports:
      - "5003:80"

  players-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${HORCUP_AZURE_PLAYERS_DB:-Server=sqldata;Database=HorCup.Players;User Id=sa;Password=Pass@word}
    ports:
      - "5004:80"

  plays-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://localhost
      - EventBusConnection=localhost
    ports:
      - "5005:80"

  statistic-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${HORCUP_AZURE_PLAYERS_DB:-Server=sqldata;Database=HorCup.Statistic;User Id=sa;Password=Pass@word}
      - EventBusConnection=localhost
    ports:
      - "5006:80"

  spa:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5007:80"

volumes:
  horcup-sqldata:
    external: false
