version : "3.4"

services :
  sql-server :
    environment :
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports :
      - "5433:1433"
    volumes :
      - horcup-sql-server:/var/opt/mssql

  rabbitmq :
    ports :
      - "15672:15672"
      - "5672:5672"

  mongodb :
    ports :
      - "27017:27017"
    volumes :
      - horcup-mongodbdata:/var/opt/mongodb
#
#  cassandradb :
#    ports :
#      - "9042:9042"
#    environment :
#      - CASSANDRA_USE_ASTRA=false
#      - CASSANDRA_USER=cassandra
#      - CASSANDRA_PASSWORD=cassandra
#      - CASSANDRA_LOCAL_DC=datacenter1
#      - CASSANDRA_CONTACT_POINTS=db:9042
#      - CASSANDRA_KEYSPACE_CQL=CREATE KEYSPACE spring_petclinic WITH REPLICATION = {'class':'SimpleStrategy','replication_factor':1};
#      - MONITORING_PROMETHEUS=false
#      - DISTRIBUTED_TRACING_ENABLED=false
#
#    volumes :
#      - horcup-cassandradbdata:/var/opt/cassandradb

  identity-api :
    environment :
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings_DefaultConnection=${HORCUP_AZURE_IDENTITY_DB:-Server=sql-server;Database=HorCup.Identity;User Id=sa;Password=Pass@word}
    ports :
      - "5002:80"

  games-api :
    environment :
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${HORCUP_AZURE_GAMES_DB:-Server=sql-server;Database=HorCup.Games;User Id=sa;Password=Pass@word}
    ports :
      - "5003:80"

  players-api :
    environment :
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${HORCUP_AZURE_PLAYERS_DB:-Server=sql-server;Database=HorCup.Players;User Id=sa;Password=Pass@word}
    ports :
      - "5004:80"

  plays-api :
    environment :
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDb__ConnectionString=mongodb://localhost
      - EventBusConnection=localhost
    ports :
      - "5005:80"

  statistic-api :
    environment :
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${HORCUP_AZURE_PLAYERS_DB:-Server=sql-server;Database=HorCup.Statistic;User Id=sa;Password=Pass@word}
      - EventBusConnection=localhost
    ports :
      - "5006:80"

  spa :
    environment :
      - ASPNETCORE_ENVIRONMENT=Production
    ports :
      - "5007:80"

volumes :
  horcup-sql-server :
    external : false

  horcup-mongodbdata :
    external : false

  horcup-cassandradbdata :
    external : false
      