version: "3.4"

services:
  #  docker-compose -f docker-compose.yml -f docker-compose.override.yml build

  #  horcup.identityserver:
  #    image: ${DOCKER_REGISTRY-}identityserver
  #    build:
  #      context: .
  #      dockerfile: src/HorCup.IdentityServer/Dockerfile
  #    environment:
  #      IDENTITY_ISSUER: "http://10.0.75.1:5001"

  horcup.presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: src/HorCup.Presentation/Dockerfile

  horcup.players:
    image: ${DOCKER_REGISTRY-}players
    build:
      context: .
      dockerfile: src/HorCup.Players/Dockerfile

  horcup.games:
    image: ${DOCKER_REGISTRY-}games
    build:
      context: .
      dockerfile: src/HorCup.Games/Dockerfile

  horcup.plays:
    image: ${DOCKER_REGISTRY-}plays
    build:
      context: .
      dockerfile: src/HorCup.Plays/Dockerfile
