version: "3.4"

services:
  #  docker-compose -f docker-compose.yml -f docker-compose.prod.yml build

  #  docker run -p 15672:15672 -p 5672:5672 masstransit/rabbitmq

  #  horcup.identityserver:
  #    image: ${DOCKER_REGISTRY-}identityserver
  #    build:
  #      context: .
  #      dockerfile: src/HorCup.IdentityServer/Dockerfile
  #    environment:
  #      IDENTITY_ISSUER: "http://10.0.75.1:5001"

  sqldata:
    image: mcr.microsoft.com/mssql/server:2019-latest

  nosqldata:
    image: mongo

  rabbitmq:
    image: masstransit/rabbitmq

  identity-api:
    image: ${DOCKER_REGISTRY-horcup}/identity.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/HorCup.IdentityServer/Dockerfile
    depends_on:
      - sqldata

  players-api:
    image: ${DOCKER_REGISTRY-horcup}/players.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/HorCup.Players/Dockerfile
    depends_on:
      - sqldata

  games-api:
    image: ${DOCKER_REGISTRY-horcup}/games.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/HorCup.Games/Dockerfile
    depends_on:
      - sqldata

  plays-api:
    image: ${DOCKER_REGISTRY-horcup}/plays.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/HorCup.Plays/Dockerfile
    depends_on:
      - nosqldata
      - rabbitmq

  horcup.presentation:
    image: ${DOCKER_REGISTRY-}presentation
    build:
      context: .
      dockerfile: src/HorCup.Presentation/Dockerfile

  statistic-api:
    image: ${DOCKER_REGISTRY-horcup}/statistic.api:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/HorCup.Statistic/Dockerfile
    depends_on:
      - rabbitmq
      - sqldata

  spa:
    image: ${DOCKER_REGISTRY-horcup}/spa:${PLATFORM:-linux}-${TAG:-latest}
    build:
      context: .
      dockerfile: src/HorCup.Presentation/Dockerfile
