version: "3.4"

services:
  horcup.games:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5004:80"

  horcup.players:
    environment:
      - ASPNETCORE_ENVIRONMENT=DevelSopment
      - ASPNETCORE_URLS=http://0.0.0.0:80
    ports:
      - "5003:80"
