version: "3.4"

services:
  horcup.plays:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5002:80

  horcup.players:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5003:80

  horcup.games:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5004:80
