version: "3.4"

services:
  horcup.presentation:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - BUILD_CONFIGURATION=Release
    ports:
      - 5002:80

  horcup.players:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5003:80

  horcup.games:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5004:80

  horcup.plays:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 5005:80
