version: "3.4"

services:
  sqldata:
    environment:
      - SA_PASSWORD=Pass@word
      - ACCEPT_EULA=Y
    ports:
      - "5433:1433"
    volumes:
      - horcup-sqldata:/var/opt/mssql

  games-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${HORCUP_AZURE_GAMES_DB:-Server=sqldata;Database=HorCup.Games;User Id=sa;Password=Pass@word}
    ports:
      - "5004:80"

  players-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionString=${HORCUP_AZURE_PLAYERS_DB:-Server=sqldata;Database=HorCup.Players;User Id=sa;Password=Pass@word}
    ports:
      - "5003:80"

volumes:
  horcup-sqldata:
    external: false
